/**
 * Bundles the dashboard's browser code into the string `src/dashboard/page.ts` serves.
 *
 * Why there is a build step at all: the console this replaces was two thousand lines of
 * JavaScript inside `scripts/dashboard.html`, which TypeScript never looked at, Biome never
 * linted (it globs `*.ts`) and no test could import a function out of. The client is real
 * modules under `src/dashboard/client/` now, and this turns them back into the one thing a
 * bundled library can rely on being able to serve: a string it carries itself.
 *
 * The output is committed, so a fresh checkout can start a dashboard without a generate step.
 * `node scripts/build-client.mjs --check` exits 1 when the committed copy no longer matches
 * its source, which is what CI should run.
 *
 * esbuild is not a direct dependency: it arrives with tsup, which bundles the library with it.
 */
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const entry = join(root, "src", "dashboard", "client", "index.ts");
const target = join(root, "src", "dashboard", "client.generated.ts");

/**
 * Sequences that would end the `<script>` element early, or open a comment the HTML parser
 * reads before the JavaScript one does. An HTML parser stops a script at the first
 * `</script` in the source, including one inside a string literal. Nothing writes those
 * today; this is so that the day somebody adds one it fails here rather than in an
 * operator's browser.
 */
const FORBIDDEN_IN_SCRIPT = ["</script", "<!--", "-->", "<script"];

/**
 * Ways to put attacker-written text into a document as markup. Every value on the page (a
 * path, a User-Agent, a captured body) is written by the client being described.
 * `tests/dashboard-page.test.ts` checks the served page for these too; catching them here
 * names the source file rather than a byte offset.
 */
const FORBIDDEN_SINKS = ["innerHTML", "outerHTML", "insertAdjacentHTML", "document.write", "eval(", "new Function"];

export async function buildClient() {
  const result = await build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    // Not minified on purpose. An operator's tool served from loopback, where a hundred
    // kilobytes costs nothing and being able to read the running page in devtools does.
    minify: false,
    target: ["es2020"],
    platform: "browser",
    legalComments: "none",
    charset: "utf8",
    write: false,
    metafile: true,
    logLevel: "silent",
  });

  const code = result.outputFiles[0].text;

  const problems = [];
  for (const sequence of FORBIDDEN_IN_SCRIPT) {
    if (code.toLowerCase().includes(sequence)) problems.push(`contains ${JSON.stringify(sequence)}, which would end or confuse its <script> element`);
  }
  for (const sink of FORBIDDEN_SINKS) {
    if (!code.includes(sink)) continue;
    // Name the module, so the fix starts in the right file.
    const sources = [];
    for (const input of Object.keys(result.metafile.inputs)) {
      const text = await readFile(join(root, input), "utf8").catch(() => "");
      if (text.includes(sink)) sources.push(relative(root, join(root, input)));
    }
    problems.push(`contains ${sink}${sources.length > 0 ? ` (in ${sources.join(", ")})` : ""}. Every value on that page is attacker-written text and reaches the document through textContent`);
  }
  if (problems.length > 0) throw new Error(`The dashboard client bundle ${problems.join("; and ")}.`);

  return `/**
 * Generated by \`node scripts/build-client.mjs\` from \`src/dashboard/client/\`. Do not edit.
 *
 * The dashboard's browser code, bundled into the string \`page.ts\` stamps into its one nonced
 * <script>. See scripts/build-client.mjs for why this exists.
 */

export const CLIENT_SCRIPT = ${JSON.stringify(code)};
`;
}

const contents = await buildClient();
const existing = await readFile(target, "utf8").catch(() => "");
const name = relative(root, target);

if (process.argv.includes("--check")) {
  if (existing !== contents) {
    console.error(`${name} is out of date. Run \`node scripts/build-client.mjs\`.`);
    process.exit(1);
  }
  console.log(`${name} is up to date`);
} else if (existing === contents) {
  console.log(`${name} unchanged (${(contents.length / 1024).toFixed(1)} kB)`);
} else {
  await writeFile(target, contents);
  console.log(`${name} written (${(contents.length / 1024).toFixed(1)} kB)`);
}
