import { defaultDecoyPaths } from "./detectors/index.js";
import type { DecoyPath } from "./detectors/index.js";

export interface RobotsTxtOptions {
  /** Decoys to advertise. Defaults to the built-in decoy set. Only exact string paths are used (regex decoys can't be a robots rule). */
  decoys?: DecoyPath[];
  /** Extra real paths to Disallow (e.g. `/admin`, `/internal`). */
  extraDisallow?: string[];
  /** A real sitemap URL to advertise, if you have one. */
  sitemap?: string;
}

/**
 * Generates a `robots.txt` that lists the honeypot's decoy paths as `Disallow`.
 * This is a lure with two effects: a legitimate crawler obeys it and never hits
 * the decoys (so they don't clutter your incidents with well-behaved bots), while
 * anything that fetches a `Disallow`ed path anyway has proven it doesn't respect
 * robots.txt — which no legitimate crawler does. Serve it from `/robots.txt`.
 */
export function generateRobotsTxt(options: RobotsTxtOptions = {}): string {
  const decoys = options.decoys ?? defaultDecoyPaths;
  const fromDecoys = decoys.filter((d): d is DecoyPath & { path: string } => typeof d.path === "string").map((d) => d.path);
  const paths = [...new Set([...fromDecoys, ...(options.extraDisallow ?? [])])].sort();

  const lines = [
    "# Generated by hackerpot. The paths below are honeypot decoys advertised as",
    "# Disallow: a legitimate crawler skips them, so anything that fetches one",
    "# anyway has identified itself as not respecting robots.txt.",
    "User-agent: *",
  ];
  for (const path of paths) lines.push(`Disallow: ${path}`);
  if (options.sitemap) lines.push("", `Sitemap: ${options.sitemap}`);
  return lines.join("\n") + "\n";
}
